services:
  db:
    image: postgres:16
    container_name: monster_db
    environment:
      POSTGRES_USER: tutorial
      POSTGRES_PASSWORD: tutorial
      POSTGRES_DB: tutorial
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: