spring.datasource.url=jdbc:postgresql://localhost:5436/tutorial
spring.datasource.username=tutorial
spring.datasource.password=tutorial
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080