CREATE TABLE habitats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    biome VARCHAR(40) NOT NULL,
    location VARCHAR(120) NOT NULL,
    min_temp_c INT NOT NULL,
    max_temp_c INT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE creatures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    species VARCHAR(120) NOT NULL,
    danger_level VARCHAR(30) NOT NULL,
    condition VARCHAR(30) NOT NULL,
    notes TEXT,
    habitat_id BIGINT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_creatures_habitats
        FOREIGN KEY (habitat_id) REFERENCES habitats(id)
);

ALTER TABLE habitats
ADD CONSTRAINT chk_habitats_biome
CHECK (biome IN ('FOREST', 'DESERT', 'OCEAN'));

ALTER TABLE creatures
ADD CONSTRAINT chk_creatures_danger_level
CHECK (danger_level IN ('LOW', 'MEDIUM', 'HIGH'));

ALTER TABLE creatures
ADD CONSTRAINT chk_creatures_condition
CHECK (condition IN ('STABLE', 'QUARANTINED', 'CRITICAL'));